Update main.yml
mo

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,32 +19,34 @@ jobs:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     defaults:
-      run: 
+      run: |
         working-directory: roles
-
+        path: /bin/bash
+        args: 
+          - -ec
+          - |
+            ls
+            echo '```' >> ../pr-message/message.txt
+            shellcheck -x **/*.sh >> ../pr-message/message.txt
+            if [ $? -eq 0 ]
+            then
+            echo "No shellcheck linting errors detected 👍 " >> ../pr-message/message.txt
+            fi
+            echo '```' >> ../pr-message/message.txt
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
       
-      - name: "Example"
-        description: "Receives file and generates output"
-        inputs:
-          file-path: # id of input
-            description: "Path to test script"
-            required: true
-            default: "*yml"
-        outputs:
-          results-file: # id of output
-            description: "Path to results file
+      
 
       # Runs github super lint command
 
-      - name: Lint Code Base
-        uses: github/super-linter@v4
-        env:
-          GITHUB_TOKEN: ${{github.token}}
+    #  - name: Lint Code Base
+      #  uses: github/super-linter@v4
+       # env:
+       #   GITHUB_TOKEN: ${{github.token}}
           
         
         
